### ISSUE TITLE
Change rendered icon page to not be SVG specific

### ISSUE THREAD

**Issue by kwalker3690** [optimizely/oui-icons#8]
We support two ways of rendering icons, svg and class name. I'd like to use the icon example page in the Canvas docs, and Canvas users will be confused when in their docs it says to use the class names, but then they look at the icon example page and are only able to copy SVGs. I propose we change the icon page to only copy the portion that is the same for SVG and class name, ie `add-16`. Then at the top of the page we could give two examples for how to render the icons and what a user should replace in each one.

**Comment by tomgenoni** [comment]
What if we had two separate example pages, one for SVG and one for classes? That should be doable. Or one example page but two buttons, one for copying class HTML and one for copying SVG HTML?

**Comment by kwalker3690** [comment]
Either of those would work for me!

**Comment by daverau-optimizely** [comment]
Since we're no longer doing Canvas apps and moving icons to React this is probably a non-issue now.
